### ISSUE TITLE
Simply git command and do not use regex

### ISSUE THREAD

**Issue by pjpsoares** [stevemao/git-semver-tags#1]
Using gitlab the response I'm getting from git log --tags --simplify-by-decoration --pretty=format:"%d" is:
 (v1.0.2)
 (v1.0.1)
 (v1.0.0)

And that breaks the matching of tags so it will return no tags for this project.

**Comment by stevemao** [comment]
Why is it different? I don't think the reason is because of gitlab, its more likely your git version or OS. Ideally I would like to get all tags without using regex. PR welcome.

**Comment by pjpsoares** [comment]
You're right regarding the OS. Just tested with mac OS and it works, just not only on windows.

**Comment by stevemao** [comment]
Is there a way to make them work on both? I don't like to use regex to do this.

**Comment by pjpsoares** [comment]
Shouldn't `git tag` work?

**Comment by stevemao** [comment]
No, `git tag` is not in reverse chronological order

**Comment by stevemao** [comment]
can you try if `git tag | xargs -I@ git log --format=format:"%ai @%n" -1 @ | sort | awk '{print $4}'` works on windows? it works on mac

Ref: http://stackoverflow.com/questions/18659959/git-tag-sorted-in-chronological-order-of-the-date-of-the-commit-pointed-to

**Comment by pjpsoares** [comment]
It doesn't work on Windows, but the git installation does provide xargs. I'm trying to understand why it doesn't work. `git tag --sort version:refname` should work from git 2.3.3 (http://stackoverflow.com/questions/21414725/show-git-tags-sorted-by-date)

**Comment by stevemao** [comment]
Do you think we should use `git tag --sort version:refname` and ask people to upgrade to git 2.3.3 ?

**Comment by pjpsoares** [comment]
I don't see why not. I think the best approach there is to release a breaking change and with that breaking change you support git +2.3.3.
That way if someone wants to use an older version they can.

**Comment by stevemao** [comment]
Cool. Thanks for the suggestion @pjpsoares :)

**Comment by pjpsoares** [comment]
Tested git tag --sort version:refname and it didn't worked perfectly.
So if you have 4.0.0 created before 2.0.0 the 2.0.0 will appear first.
But if you have 1.0.15 and 1.0.2. The order will be 1.0.2 and then 1.0.15 regardless of the creation date.

**Comment by stevemao** [comment]
> Note: since lightweight tags do not store date information, the date of a semver is the date of the commit that is tagged on. If two semver tags on one commit, the order is not guaranteed.

Are you talking about the date of commit tagged on? It has to be in reverse chronological order.

**Comment by pjpsoares** [comment]
The date of the creation of the tag.

**Comment by stevemao** [comment]
lightweight tags do not store any extra information.

**Comment by Rayman** [comment]
Maybe the following command could generate a more stable output:

```
$ git for-each-ref --sort=taggerdate --format '%(refname)' refs/tags
```

On my old git (1.7.9.5) it outputs a correct sorted order:

```
refs/tags/v0.0.1
refs/tags/v0.0.2
refs/tags/v0.0.3
refs/tags/v0.1.0
refs/tags/v0.1.2
refs/tags/v0.1.3
refs/tags/v0.2.0
refs/tags/v0.2.1
refs/tags/v0.2.2
refs/tags/v0.3.0
refs/tags/v0.4.0
refs/tags/v0.4.1
```

**Comment by stevemao** [comment]
@Rayman it's not in the right order.

**Comment by stevemao** [comment]
The order needs to be reverse chronological order

**Comment by NicBright** [comment]
What do you mean by chronological order? What I think you mean is this:

If I add tag 2.0.0 today, and tomorrow I'll do a bugfix in the old v1 branch (let's say 1.5.3). Then what you want is to have the 1.5.3 sandwiched in between 2.0.0 and future versions (let's say 2.0.1)?

**Comment by stevemao** [comment]
@NicBright Yes.

**Comment by psyrendust** [comment]
How about using `git tag`, then sorting using https://www.npmjs.com/package/semver-sort

**Comment by stevemao** [comment]
Well the result I want is not in semver order. You could release `2.0.0` first then `1.8.1`.

**Comment by psyrendust** [comment]
`git tag` should spit out version numbers in ascending semver order like so:

``` shell
± |master ✓| → git tag
v0.0.1
v1.0.0
v1.1.0
v1.1.1
v1.2.0
v2.1.0
```

I created `v2.1.0` first, then later created `v1.2.0`. But regardless of the order you can use `semverSort.desc()` to get them in reverse semver order.

So the code would look like this:

``` js
'use strict';
var exec = require('child_process').exec;
var semverSort = require('semver-sort');
var semverValid = require('semver').valid;
var cmd = 'git tag';

module.exports = function(callback) {
  exec(cmd, {
    maxBuffer: Infinity
  }, function(err, data) {
    if (err) {
      callback(err);
      return;
    }

    var tags = [];

    data.split('\n').forEach(function(tag) {
      if (semverValid(tag)) {
        tags.push(tag);
      }
    });

    callback(null, semverSort.desc(tags));
  });
};
```

This would allow you to use `git tag`, and it also doesn't output any ansi text since there is no colored output for `git tag`. It also removes the need for regex and should output an array in reverse order like this:

```
[
  v2.1.0,
  v1.2.0,
  v1.1.1,
  v1.1.0,
  v1.0.0,
  v0.0.1
]
```

**Comment by psyrendust** [comment]
I just tried to run the tests from the code above and got a couple of errors. I feel that the two test fixtures might be wrong.

``` shell
  1) should error if no commits found
  ✓ should get no semver tags (225ms)
  ✓ should get the semver tag (416ms)
  ✓ should get both semver tags (110ms)
  ✓ should get all semver tags if two tags on the same commit (113ms)
  ✓ should still work if I run it again
  2) should be in reverse chronological order
  3) should work with prerelease
  ✓ should work with empty commit (537ms)

  6 passing (2s)
  3 failing

  1)  should error if no commits found:
     Uncaught AssertionError: null == true
      at test.js:17:5
      at index.js:24:5
      at ChildProcess.exithandler (child_process.js:194:7)
      at maybeClose (internal/child_process.js:818:16)
      at Socket.<anonymous> (internal/child_process.js:319:11)
      at Pipe._onclose (net.js:469:12)

  2)  should be in reverse chronological order:

      Uncaught AssertionError: [ 'v4.0.0', 'v3.0.0', 'v2.0.0', 'v1.0.0' ] deepEqual [ 'v1.0.0', 'v4.0.0', 'v3.0.0', 'v2.0.0' ]
      + expected - actual

       [
      +  "v1.0.0"
         "v4.0.0"
         "v3.0.0"
         "v2.0.0"
      -  "v1.0.0"
       ]

      at test.js:84:5
      at index.js:24:5
      at ChildProcess.exithandler (child_process.js:194:7)
      at maybeClose (internal/child_process.js:818:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

  3)  should work with prerelease:

      Uncaught AssertionError: [ '5.0.0-pre', 'v4.0.0', 'v3.0.0', 'v2.0.0', 'v1.0.0' ] deepEqual [ '5.0.0-pre', 'v1.0.0', 'v4.0.0', 'v3.0.0', 'v2.0.0' ]
      + expected - actual

       [
         "5.0.0-pre"
      +  "v1.0.0"
         "v4.0.0"
         "v3.0.0"
         "v2.0.0"
      -  "v1.0.0"
       ]

      at test.js:96:5
      at index.js:24:5
      at ChildProcess.exithandler (child_process.js:194:7)
      at maybeClose (internal/child_process.js:818:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

**Comment by psyrendust** [comment]
I did the test again but did a console log of the original order and then the sorted order and got this:

``` shell
before
sorted
  1) should error if no commits found
before
sorted
  ✓ should get no semver tags (228ms)
before v2.0.0
sorted v2.0.0
  ✓ should get the semver tag (422ms)
before v2.0.0,v3.0.0
sorted v3.0.0,v2.0.0
  ✓ should get both semver tags (110ms)
before v2.0.0,v3.0.0,v4.0.0
sorted v4.0.0,v3.0.0,v2.0.0
  ✓ should get all semver tags if two tags on the same commit (114ms)
before v2.0.0,v3.0.0,v4.0.0
sorted v4.0.0,v3.0.0,v2.0.0
  ✓ should still work if I run it again
before v1.0.0,v2.0.0,v3.0.0,v4.0.0
sorted v4.0.0,v3.0.0,v2.0.0,v1.0.0
  2) should be in reverse chronological order
before 5.0.0-pre,v1.0.0,v2.0.0,v3.0.0,v4.0.0
sorted 5.0.0-pre,v4.0.0,v3.0.0,v2.0.0,v1.0.0
  3) should work with prerelease
before v1.1.0
sorted v1.1.0
  ✓ should work with empty commit (535ms)

  6 passing (2s)
  3 failing

  1)  should error if no commits found:
     Uncaught AssertionError: null == true
      at test.js:17:5
      at index.js:27:5
      at ChildProcess.exithandler (child_process.js:194:7)
      at maybeClose (internal/child_process.js:818:16)
      at Socket.<anonymous> (internal/child_process.js:319:11)
      at Pipe._onclose (net.js:469:12)

  2)  should be in reverse chronological order:

      Uncaught AssertionError: [ 'v4.0.0', 'v3.0.0', 'v2.0.0', 'v1.0.0' ] deepEqual [ 'v1.0.0', 'v4.0.0', 'v3.0.0', 'v2.0.0' ]
      + expected - actual

       [
      +  "v1.0.0"
         "v4.0.0"
         "v3.0.0"
         "v2.0.0"
      -  "v1.0.0"
       ]

      at test.js:84:5
      at index.js:27:5
      at ChildProcess.exithandler (child_process.js:194:7)
      at maybeClose (internal/child_process.js:818:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

  3)  should work with prerelease:

      Uncaught AssertionError: [ '5.0.0-pre', 'v4.0.0', 'v3.0.0', 'v2.0.0', 'v1.0.0' ] deepEqual [ '5.0.0-pre', 'v1.0.0', 'v4.0.0', 'v3.0.0', 'v2.0.0' ]
      + expected - actual

       [
         "5.0.0-pre"
      +  "v1.0.0"
         "v4.0.0"
         "v3.0.0"
         "v2.0.0"
      -  "v1.0.0"
       ]

      at test.js:96:5
      at index.js:27:5
      at ChildProcess.exithandler (child_process.js:194:7)
      at maybeClose (internal/child_process.js:818:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

So this is the order that the test is expecting:
`[ '5.0.0-pre', 'v1.0.0', 'v4.0.0', 'v3.0.0', 'v2.0.0' ]`

To me it seems like `v1.0.0` should be at the end of the array if it were to be sorted in reverse semver order, and not by when it was created. It should look like this:
`[ '5.0.0-pre', 'v4.0.0', 'v3.0.0', 'v2.0.0', 'v1.0.0' ]`

@stevemao tell me if I'm wrong about this assumption with the reverse sort order. Are you wanting it to be in reverse chronological order (most recent first) or in reverse semver order (highest semver first)?

**Comment by Rayman** [comment]
He wants reverse chronological order. 

The following command works for annotated tags:

```
git for-each-ref --sort=-taggerdate --format '%(refname:short) %(taggerdate:iso)' refs/tags
```

Lightweight tags are unfortunately simply appended to the end. I've not yet found something that works for mixed lightweight and annotated tags.

**Comment by psyrendust** [comment]
What if you stuck with the old way of doing:

```
git log --tags --simplify-by-decoration --pretty=format:"%d"
```

Which would give you tags in reverse chronological order:

```
 (tag: v2.1.0)
 (tag: v2.0.1)
 (tag: v2.1.1)
 (tag: v2.0.0)
 (tag: v1.2.4)
 (tag: v1.2.3)
 (tag: v1.2.2)
 (tag: v1.2.1)
 (tag: v1.2.0)
 (tag: v1.1.0)
 (tag: v1.0.0)
 (tag: v0.0.2)
 (tag: v0.0.1)
```

or in the case of @pjpsoares you would get:

```
(v2.1.0)
(v2.0.1)
(v2.1.1)
(v2.0.0)
(v1.2.4)
(v1.2.3)
(v1.2.2)
(v1.2.1)
(v1.2.0)
(v1.1.0)
(v1.0.0)
(v0.0.2)
(v0.0.1)
```

Using the following js regex `\((tag:\s*)*(.+?)[,\)]` you should get the following output:

```
 v2.1.0
 v2.0.1
 v2.1.1
 v2.0.0
 v1.2.4
 v1.2.3
 v1.2.2
 v1.2.1
 v1.2.0
 v1.1.0
 v1.0.0
 v0.0.2
 v0.0.1
```

Or you could do this all with git log and sed to get the same output:

```
git log --tags --simplify-by-decoration --pretty=format:"%d" | sed 's/(tag:[[:space:]]*//g' | sed 's/)//g'
```

**Comment by stevemao** [comment]
Does the command pass the tests?

**Comment by stevemao** [comment]
reverse chronological order makes the most sense here, agree?

**Comment by psyrendust** [comment]
I tried it with `sed` and wasn't have very good luck with the tests passing.

**Comment by cueedee** [comment]
How about using `git tag` to get all tags, retrieve the author date as a UNIX timestamp for each using `git show -s --pretty='%at' <tag>` and sort on that?

**Comment by stevemao** [comment]
@cueedee have you tested that on your local machine? Do all test pass?

**Comment by cueedee** [comment]
@stevemao, can't say that I did. At this point, it's just an idea.

I see that other work (#6) is also underway to make the dependency on the `git` cli obsolete. So it may no longer be worthwhile to explore if the idea is viable?

**Comment by stevemao** [comment]
I think it still does.

**Comment by blowsie** [comment]
I'm not sure if I'm missing one of the requirements here but this change is working for me

```
var regex = /\(tag:\s*(.+?)[,\)]/gi;
var cmd = 'git log --tags --simplify-by-decoration --pretty=format:"%d"';
```

It seems more robust to me since, it is no longer iterating rows which are not tags.

---

This for me, fixed my problem with git-semver tags not picking up some of my tags.
Let me know what you think, I can run the tests

**Comment by blowsie** [comment]
I am unable to run the tests, perhaps someone else could try ?

**Comment by stevemao** [comment]
@blowsie PR is always welcome :)

**Comment by bcoe** [comment]
see: https://github.com/conventional-changelog/conventional-changelog/issues/164
