### ISSUE TITLE
semverValid returns null if git log outputs ansi characters for colored output

### ISSUE THREAD

**Issue by psyrendust** [stevemao/git-semver-tags#4]
If there is colored output from running `git log --decorate` the text will contain ansi characters. If you try and validate the semver string with ansi characters present `semver.valid()` will return `null`. If that is the case `git-semver-tags` will return no results.

**Comment by stevemao** [comment]
Interesting! Why is it not failing on the CI?

**Comment by psyrendust** [comment]
When I run `git log --decorate` I get this colored output:

![image](https://cloud.githubusercontent.com/assets/928502/12663976/12d2821e-c5e1-11e5-8ca0-9c77cf91845b.png)

**Comment by stevemao** [comment]
hm... I just wanna know why it is different on you machine and on CI (also passed on my machine) so we might find other potential problems and add related test for your case.

**Comment by stevemao** [comment]
It looks similar to yours on my Mac too. What's your git version?

**Comment by psyrendust** [comment]
Here is my system info:

```
System Info

Software:

    System Software Overview:

      System Version: OS X 10.11.3 (15D21)
      Kernel Version: Darwin 15.3.0
      Time since boot: 7 days 7:42
      Bash Version: 4.3.42
      Zsh Version:  5.2
      Git Version:  2.7.0
      Node Version: 4.2.2
      NPM Version:  2.14.14

Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro11,5
      Processor Name: Intel Core i7
      Processor Speed: 2.8 GHz
      Number of Processors: 1
      Total Number of Cores: 4
      L2 Cache (per Core): 256 KB
      L3 Cache: 6 MB
      Memory: 16 GB
      Boot ROM Version: MBP114.0172.B07
      SMC Version (system): 2.30f2
```

I use Zsh for my shell and oh-my-zsh.

**Comment by stevemao** [comment]
> I use Zsh for my shell and oh-my-zsh.

Probably why.
