### ISSUE TITLE
regex doesn't work if commit has multiple tags

### ISSUE THREAD

**Issue by jpnelson** [stevemao/git-semver-tags#8]
This might be the same as #1 . If you have multiple commits on a tag, it will not recognise the fact that one of the tags is the semantic one, as `git log --decorate --no-color` outputs them in reverse alphabetical order, and the regex only matches the first one.

**Comment by stevemao** [comment]
> one of the tags is the semantic one

What do you mean? 
If multiple tags on one commit the order of the tags doesn't matter.

**Comment by jpnelson** [comment]
At this line: https://github.com/stevemao/git-semver-tags/blob/master/index.js#L21

The first match is returned, when there may actually be multiple tags. The first tag matched may not be the semver tag.

**Comment by stevemao** [comment]
> The first match is returned, when there may actually be multiple tags. The first tag matched may not be the semver tag.

I don't think so.. it's not the first match. It's the first capturing group. See https://regex101.com/r/hK4vQ9/1

Also see the tests: https://github.com/stevemao/git-semver-tags/blob/master/test.js#L41-L68
va.b.c, v4.0.0, and v3.0.0 are on the same commit and it actually gets both v4.0.0, and v3.0.0. 

I might miss something here? If you could send a PR with failure test that would be more clear. Thanks!

**Comment by stevemao** [comment]
@jpnelson I'm closing this now because I don't think this is valid.
